export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY'
export const VALIDATE = 'VALIDATE'
export const LOGOUT = 'LOGOUT'
export const SET_AVATAR = 'SET_AVATAR'
export const GET_SLIDERS = 'GET_SLIDERS'
